Refactor scripts
mynguyenlgg/RestAssuredFramework pull request #10
Opened 2024-03-06 05:01 UTC by mynguyenlgg

2024-03-06 06:50 UTC, truongdnascript commented on .github/workflows/regression.yml
> +      - name: Update test_config.json values
We don't need it, use the environment variable, you can set the value for them in real-time

2024-03-06 06:52 UTC, truongdnascript commented on src/main/java/com/client/request/BaseClient.java
> +            .addQueryParam("token", testconfig.getAppToken())
If the API (eg login) does not require the token/key what should you do

2024-03-06 06:52 UTC, truongdnascript commented on src/main/java/com/client/request/BaseClient.java
> +            .log(LogDetail.ALL).
Why log all?

2024-03-06 06:53 UTC, truongdnascript commented on src/main/resources/config/test_config.json
> +  "appKey": "cdceab0688f6033931a439e74f68bc78",
should remove secret

2024-03-06 06:54 UTC, truongdnascript commented on src/main/java/com/client/request/BaseClient.java
> +    protected RequestSpecification requestSender = RestAssured.given(requestSpecification);
requestSender ->  request

2024-03-06 07:13 UTC, phamthai1912 requested changes

2024-03-06 07:13 UTC, phamthai1912 commented on src/main/java/com/client/response/ResponseClient.java
> +//    public String getSchema(File path) {
remove this method  as redundant

2024-03-06 07:13 UTC, phamthai1912 commented on src/test/java/com/client/tests/BoardTests.java
> +        assertTrue(res.isSuccessful());
I think we should verify status code is 200 or 201, it will show clearly the expected/actual status code on report instead of True/False

2024-03-06 07:13 UTC, phamthai1912 commented on src/main/java/com/client/request/BoardClient.java
> +    @Step
pls add description of @Step

2024-03-06 10:39 UTC, mynguyenlgg commented on src/main/java/com/client/request/BoardClient.java
> +    @Step
The step will show the name of function if we add description. Because there are many functions in project, so some cases we can skip to add the description unless the function is confused.

2024-03-07 02:36 UTC, mynguyenlgg commented on .github/workflows/regression.yml
> +      - name: Update test_config.json values
I updated

2024-03-07 02:36 UTC, mynguyenlgg commented on src/main/java/com/client/request/BaseClient.java
> +            .addQueryParam("token", testconfig.getAppToken())
I updated

2024-03-07 02:37 UTC, mynguyenlgg commented on src/main/java/com/client/request/BaseClient.java
> +            .log(LogDetail.ALL).
I updated

2024-03-07 02:37 UTC, mynguyenlgg commented on src/main/resources/config/test_config.json
> +  "appKey": "cdceab0688f6033931a439e74f68bc78",
I updated

2024-03-07 02:37 UTC, mynguyenlgg commented on src/main/java/com/client/request/BaseClient.java
> +    protected RequestSpecification requestSender = RestAssured.given(requestSpecification);
I updated

2024-03-07 02:37 UTC, mynguyenlgg commented on src/test/java/com/client/tests/BoardTests.java
> +        if (boardID != null) {
I updated

2024-03-07 02:37 UTC, mynguyenlgg commented on src/main/java/com/client/response/ResponseClient.java
> +//    public String getSchema(File path) {
I updated

2024-03-07 02:37 UTC, mynguyenlgg commented on src/test/java/com/client/tests/BoardTests.java
> +        assertTrue(res.isSuccessful());
I updated

2024-03-07 04:28 UTC, phamthai1912 requested changes

2024-03-07 04:28 UTC, phamthai1912 commented on src/main/java/com/client/config/Configuration.java
>  @Setter
I think we can add @Getter and remove get...() methods below

2024-03-07 04:28 UTC, phamthai1912 commented on src/main/java/com/client/request/BaseClient.java
>                  .log(LogDetail.ALL)
remove this

2024-03-07 04:28 UTC, phamthai1912 commented on src/main/java/com/client/request/BoardClient.java
> +@Slf4j
remove this

2024-03-07 04:48 UTC, dinhbao10t4 commented on src/main/java/com/client/request/BoardClient.java
> +        super();
No need call super()

2024-03-07 04:48 UTC, dinhbao10t4 commented on src/test/java/com/client/tests/Board/TC001_CreateBoard.java
> +    BoardClient boardApi = new BoardClient();
rename boardApi to boardClient to consistent. Do the same thing in TC002_GetBoard, TC003_DeleteBoard

2024-03-08 02:19 UTC, truongdnascript commented on src/main/java/com/client/services/BaseService.java
> +    protected ResponseClient pathParamsRequest(Method method, Map<String, ?> params, String path) {
What does it mean? pathParamsRequest

2024-03-08 02:19 UTC, truongdnascript commented on src/main/java/com/client/services/BaseService.java
> +    protected ResponseClient queryParamsRequest(Method method, Map<String, ?> params, String path) {
What does it mean?

2024-03-08 02:20 UTC, truongdnascript commented on src/main/java/com/client/services/BoardService.java
> +    protected RequestSpecification getRequestSpec() {
Why need to override it?

2024-03-11 03:09 UTC, dinhbao10t4 commented on src/main/java/com/client/config/Configuration.java
> +public class Configuration {
apply the Singleton pattern, So adding a private constructor to prevent users create new instance anywhere.

2024-03-11 03:09 UTC, dinhbao10t4 commented on src/main/java/com/client/services/ParamsBuilder.java
> +@Data
Use @Getter, @Setter instead of @Data

2024-03-11 03:43 UTC, dinhbao10t4 approved these changes

2024-03-11 03:47 UTC, mynguyenlgg commented on src/main/java/com/client/services/ParamsBuilder.java
> +@Data
I updated

2024-03-11 03:47 UTC, mynguyenlgg commented on src/main/java/com/client/config/Configuration.java
> +public class Configuration {
I updated

2024-03-11 03:47 UTC, merged